### ISSUE TITLE
Doesn't rename materialized views

### ISSUE THREAD

**Issue by jhnns** [bkniffler/hasura-camelize#5]
Since materialized views don't show up in the `information_schema` (there's an [interesting thread](https://www.postgresql.org/message-id/3794.1412980686%40sss.pgh.pa.us) about this), `hasura-camelize` will miss materialized views. Hasura itself, however, *does* recognize materialized views and will display them just as regular views.

The problem with materialized views is that there's no SQL standard. Every DB has a different way of introspection. E.g. with Postgres you can do:

```sql
SELECT schemaname, matviewname
FROM pg_matviews
```

but that won't work for other DBs.

What do you think? How should `hasura-camelize` handle materialized views?

**Comment by bkniffler** [comment]
Just added a new version 1.2.2, added a param `pgMaterializedViews` as seen on the updated readme. You'll find the code for fetching the views and their column names here: https://github.com/bkniffler/hasura-camelize/blob/master/src/api.ts#L50

Let me know if it works, and thanks for bringing it up :)

**Comment by bkniffler** [comment]
For future changes, I'm open to add db specific features @jhnns. For now we can keep things simple by using flags, but at some point, if we add more features, we can always streamline the arguments, add automatic detection for db engine etc.

**Comment by jhnns** [comment]
Wow that was quick! The flag works for me, thanks 🙏 

> For future changes, I'm open to add db specific features @jhnns. For now we can keep things simple by using flags, but at some point, if we add more features, we can always streamline the arguments, add automatic detection for db engine etc.

Sounds good 👍
